stages:
  - build
  - push
  - run
  - clean

build:
  stage: build
  script:
    - /usr/local/maven/apache-maven-3.5.3/bin/mvn clean package
    - cp target/itoken-zuul-1.0.0-SNAPSHOT.jar docker
    - cd docker
    - docker build -t 10.0.2.27:5000/itoken-zuul .

push:
  stage: push
  script:
    - docker push 10.0.2.27:5000/itoken-zuul

run:
  stage: run
  script:
    - cd docker
    - docker-compose down
    - docker-compose up -d

clean:
  stage: clean
  script:
    - docker rmi -f $(docker images -q -f dangling=true)
